### ISSUE TITLE
Inquiery about running on a regular OS

### ISSUE THREAD

**Issue by guilyx** [ros2-realtime-demo/pendulum#20]
Hi,

I've been working on quite a few projects involving real-time and I've just found this. I was wondering what was the expected results when running the demo on a non-realtime OS ( i.e. Ubuntu, no RT Preempt, no Xenomai) 

I've tried comparing myself, using the statistics messages and comparing between a Xenomai patched Linux and a regular Kernel, and found out that jitters are much slimmer on my Xenomai, but involuntary context switches are much bigger. Wondered why ?

Shoudn't it be one of those cases : 
- statistics are drastically better on the RTOS
- statistics are unrelevant/the stack shouldn't even be ran on a regular OS

Trying to self-teach by lurking around those kinds of projects, so I've tons of info to pick up from you. 

EDIT : it's neither a bug nor a feature request so I've just picked one, if you want to update the label.

**Comment by carlossvg** [comment]
Hi @guilyx, thank you for the feedback. 

>statistics are drastically better on the RTOS

Definitely this should be the case. You could get lower latencies on average in a non-real-time kernel, but worst case latencies should always be lower in an RTOS if the application and the system are correctly configured.

There could be several reasons you are getting more involuntary context switches. It could be caused by a thread from the same process with the same or higher priority than the one used to run the executor. In this case, the candidates would be thread used to simulate the pendulum physics or a thread from the DDS (in case they are inheriting the priority of the main process). Additionally, it could be caused by another real-time thread from the kernel with a higher priority. One way to confirm this would be to use a tracer to check which thread(s) are preempting the executor thread. You could use ros2_tracing, lttng or ftrace for example. 

In any case, don't be surprised if you find inconsistencies in the results using this demo. We developed this project in our free time and unfortunately, we couldn't spend much time testing it thoroughly, fix bugs, and do some necessary refactoring. 

In the meanwhile, I suggest you take a look at this project which is under active development: https://github.com/hsgwa/ros2_timer_latency_measurement. 

This project works also as a real-time benchmark for ROS 2 but is a more simple scenario. There is only one thread, no services, and no DDS communications involved. This makes it easier to reason about the results, which is a good starting point to compare different RTOS or different setups. 

Hopefully, in the future, we could expend more time with this project and continue working on all the open issues we have.

**Comment by guilyx** [comment]
Thanks for all the information ! This will help getting the research further. You can close :+1:
