### ISSUE TITLE
Ros2 Crystal support required

### ISSUE THREAD

**Issue by Viplav04** [ros2-realtime-demo/pendulum#5]
Ros2 crystal has already a pendulum_demo as part of the debian package installed.
Can you suggest which packages need to be added to it and how they can be added to the crystal demo to visualise it in the rviz ?

**Comment by carlossvg** [comment]
I think there is a confusion here so I will try to clarify it. We are talking about two completely projects. First we have the demo you mention in [pendulum demo in ros2/demos](https://github.com/ros2/demos/blob/master/pendulum_control) (called `pendulum_control`). Second we have the pendulum demo of this project which is a new project  created from scratch and is not compatible with the pendulum_control demo.

There are several reasons both projects are not compatible (architecture, msgs, model, packages, etc...). I'm afraid it is not possible to use any part of this project to add visualization to the pendulum_control demo. In any case I don't recommend you to do it because the simulation of that demo is not complete so you would observe a broken simulation. 

I would recommend you to just use this demo with crystal. The development was done with dashing so we haven't yet done a clear separation between releases (but we should do it). It would be great if  can test this demo with crystal and what is is not working. With this information we could backport some parts to crystal. Then we would create two separate branches, one for crystal and one for dashing.

**Comment by LanderU** [comment]
Hi @Viplav04 , thanks for your issue!

I'll try to run this project using crystal  to see the compatibility.
I'll report here the progress.

**Comment by Viplav04** [comment]
Hello @carlossvg  & @LanderU 
Thank you for the reply.
Yes, I know it is not compatible as the way to call the nodes is different in crystal and dashing. But I was just thinking that if we could just make a few changes in the packages to visualise the demo in rviz & use the pendulum control crystal packages for the motor and sensor and combine them.
I will also try to backport it and report if I am successful.

**Comment by Viplav04** [comment]
@carlossvg  Ok, But i was thinking if I can backport this repo and create new nodes for pendulum motor  sensor and controller, as there is a difference between the node initialisation code for crystal and dashing. Will that work well with the simulation?

**Comment by carlossvg** [comment]
Yes, simulation in this project doesn't depend on any ROS feature so that would be ok. I think we only need to make minor changes to make it compatible with crystal.

**Comment by Viplav04** [comment]
HI, I was also thinking to test different DDS and QoS settings with the real time demo. Any documentation on how to change the DDS by command line or will I have to change the source code?

**Comment by carlossvg** [comment]
The DDS configuration from ROS 2 is quite limited (See [this](https://discourse.ros.org/t/a-more-unified-and-standard-way-of-configuring-the-dds-layer/11372) for example). At this point they way you have to configure each DDS is by setting the QoS profile configuration file. The configuration parameters depends on each DDS implementation so you will need to take a look to the documentation to tune them. Here you have some links that may help you:

* FastRTPS: https://roscon.ros.org/2017/presentations/ROSCon%202017%20ROS2%20Fine%20Tuning.pdf, https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html
* RTI Connext pro: https://research.rti.com/rti-doc/500/ndds.5.0.0/doc/html/api_cpp/index.html
* Opensplice: http://download.ist.adlinktech.com/docs/Vortex/html/ospl/ConfGuide/index.html
* Cyclone: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst, https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md
* ...

You probably want to take a took configuration parameters relevant to real-time such as thread priorities, memory locking, etc.

In any case I think this topic deviates from the main topic of this issue. I suggest you to open a new issue and continue the discussion in that one.

**Comment by LanderU** [comment]
I think we should move this question and the answer to a new issue for more visibility.

**Comment by LanderU** [comment]
After some internal discussions, we've decided to not include support for crystal because the support is finished: https://index.ros.org/doc/ros2/Releases/

If you still have interest on porting the project to crystal, feel free to open a new PR using the guidelines and we'll have a look.

**Comment by LanderU** [comment]
Closing this issue. Feel free to reopen or continue writing if you need it.
